// source: product.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var seo_pb = require('./seo_pb.js');
goog.object.extend(proto, seo_pb);
var sql_pb = require('./sql_pb.js');
goog.object.extend(proto, sql_pb);
var image_pb = require('./image_pb.js');
goog.object.extend(proto, image_pb);
var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.ding4.Photo', null, global);
goog.exportSymbol('proto.ding4.Product', null, global);
goog.exportSymbol('proto.ding4.ProductLink', null, global);
goog.exportSymbol('proto.ding4.ProductSpec', null, global);
goog.exportSymbol('proto.ding4.Spec', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ding4.Product = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ding4.Product.repeatedFields_, null);
};
goog.inherits(proto.ding4.Product, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ding4.Product.displayName = 'proto.ding4.Product';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ding4.Spec = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ding4.Spec.repeatedFields_, null);
};
goog.inherits(proto.ding4.Spec, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ding4.Spec.displayName = 'proto.ding4.Spec';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ding4.Photo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ding4.Photo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ding4.Photo.displayName = 'proto.ding4.Photo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ding4.ProductLink = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ding4.ProductLink.repeatedFields_, null);
};
goog.inherits(proto.ding4.ProductLink, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ding4.ProductLink.displayName = 'proto.ding4.ProductLink';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ding4.ProductSpec = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ding4.ProductSpec.repeatedFields_, null);
};
goog.inherits(proto.ding4.ProductSpec, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ding4.ProductSpec.displayName = 'proto.ding4.ProductSpec';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ding4.Product.repeatedFields_ = [13,20,21];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ding4.Product.prototype.toObject = function(opt_includeInstance) {
  return proto.ding4.Product.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ding4.Product} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ding4.Product.toObject = function(includeInstance, msg) {
  var f, obj = {
    productId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    status: jspb.Message.getFieldWithDefault(msg, 2, 0),
    code: jspb.Message.getFieldWithDefault(msg, 3, ""),
    name: (f = msg.getName()) && google_protobuf_struct_pb.Value.toObject(includeInstance, f),
    cost: jspb.Message.getFieldWithDefault(msg, 5, 0),
    price: jspb.Message.getFieldWithDefault(msg, 6, 0),
    reduce: jspb.Message.getFieldWithDefault(msg, 7, 0),
    weight: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    isPreorder: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    isPickup: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    isLinked: jspb.Message.getBooleanFieldWithDefault(msg, 11, false),
    specxMap: (f = msg.getSpecxMap()) ? f.toObject(includeInstance, proto.ding4.Spec.toObject) : [],
    photoxList: jspb.Message.toObjectList(msg.getPhotoxList(),
    proto.ding4.Photo.toObject, includeInstance),
    link: (f = msg.getLink()) && proto.ding4.ProductLink.toObject(includeInstance, f),
    labelxMap: (f = msg.getLabelxMap()) ? f.toObject(includeInstance, undefined) : [],
    operator: jspb.Message.getFieldWithDefault(msg, 17, ""),
    createAt: (f = msg.getCreateAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updateAt: (f = msg.getUpdateAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    colsList: (f = jspb.Message.getRepeatedField(msg, 20)) == null ? undefined : f,
    conditionList: jspb.Message.toObjectList(msg.getConditionList(),
    sql_pb.Condition.toObject, includeInstance),
    self: (f = msg.getSelf()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ding4.Product}
 */
proto.ding4.Product.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ding4.Product;
  return proto.ding4.Product.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ding4.Product} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ding4.Product}
 */
proto.ding4.Product.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStatus(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 4:
      var value = new google_protobuf_struct_pb.Value;
      reader.readMessage(value,google_protobuf_struct_pb.Value.deserializeBinaryFromReader);
      msg.setName(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCost(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPrice(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setReduce(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setWeight(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsPreorder(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsPickup(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsLinked(value);
      break;
    case 12:
      var value = msg.getSpecxMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.ding4.Spec.deserializeBinaryFromReader, "", new proto.ding4.Spec());
         });
      break;
    case 13:
      var value = new proto.ding4.Photo;
      reader.readMessage(value,proto.ding4.Photo.deserializeBinaryFromReader);
      msg.addPhotox(value);
      break;
    case 15:
      var value = new proto.ding4.ProductLink;
      reader.readMessage(value,proto.ding4.ProductLink.deserializeBinaryFromReader);
      msg.setLink(value);
      break;
    case 16:
      var value = msg.getLabelxMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readInt32, null, "", 0);
         });
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setOperator(value);
      break;
    case 18:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreateAt(value);
      break;
    case 19:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdateAt(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.addCols(value);
      break;
    case 21:
      var value = new sql_pb.Condition;
      reader.readMessage(value,sql_pb.Condition.deserializeBinaryFromReader);
      msg.addCondition(value);
      break;
    case 22:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setSelf(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ding4.Product.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ding4.Product.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ding4.Product} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ding4.Product.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProductId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getName();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_struct_pb.Value.serializeBinaryToWriter
    );
  }
  f = message.getCost();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getReduce();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getWeight();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getIsPreorder();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getIsPickup();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getIsLinked();
  if (f) {
    writer.writeBool(
      11,
      f
    );
  }
  f = message.getSpecxMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(12, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.ding4.Spec.serializeBinaryToWriter);
  }
  f = message.getPhotoxList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      proto.ding4.Photo.serializeBinaryToWriter
    );
  }
  f = message.getLink();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      proto.ding4.ProductLink.serializeBinaryToWriter
    );
  }
  f = message.getLabelxMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(16, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeInt32);
  }
  f = message.getOperator();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getCreateAt();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdateAt();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getColsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      20,
      f
    );
  }
  f = message.getConditionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      21,
      f,
      sql_pb.Condition.serializeBinaryToWriter
    );
  }
  f = message.getSelf();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
};


/**
 * optional string product_id = 1;
 * @return {string}
 */
proto.ding4.Product.prototype.getProductId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.setProductId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 status = 2;
 * @return {number}
 */
proto.ding4.Product.prototype.getStatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.setStatus = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string code = 3;
 * @return {string}
 */
proto.ding4.Product.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional google.protobuf.Value name = 4;
 * @return {?proto.google.protobuf.Value}
 */
proto.ding4.Product.prototype.getName = function() {
  return /** @type{?proto.google.protobuf.Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Value, 4));
};


/**
 * @param {?proto.google.protobuf.Value|undefined} value
 * @return {!proto.ding4.Product} returns this
*/
proto.ding4.Product.prototype.setName = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.clearName = function() {
  return this.setName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.Product.prototype.hasName = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int32 cost = 5;
 * @return {number}
 */
proto.ding4.Product.prototype.getCost = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.setCost = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 price = 6;
 * @return {number}
 */
proto.ding4.Product.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.setPrice = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 reduce = 7;
 * @return {number}
 */
proto.ding4.Product.prototype.getReduce = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.setReduce = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional double weight = 8;
 * @return {number}
 */
proto.ding4.Product.prototype.getWeight = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.setWeight = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional bool is_preorder = 9;
 * @return {boolean}
 */
proto.ding4.Product.prototype.getIsPreorder = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.setIsPreorder = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional bool is_pickup = 10;
 * @return {boolean}
 */
proto.ding4.Product.prototype.getIsPickup = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.setIsPickup = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional bool is_linked = 11;
 * @return {boolean}
 */
proto.ding4.Product.prototype.getIsLinked = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.setIsLinked = function(value) {
  return jspb.Message.setProto3BooleanField(this, 11, value);
};


/**
 * map<string, Spec> specx = 12;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.ding4.Spec>}
 */
proto.ding4.Product.prototype.getSpecxMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.ding4.Spec>} */ (
      jspb.Message.getMapField(this, 12, opt_noLazyCreate,
      proto.ding4.Spec));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.clearSpecxMap = function() {
  this.getSpecxMap().clear();
  return this;};


/**
 * repeated Photo photox = 13;
 * @return {!Array<!proto.ding4.Photo>}
 */
proto.ding4.Product.prototype.getPhotoxList = function() {
  return /** @type{!Array<!proto.ding4.Photo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ding4.Photo, 13));
};


/**
 * @param {!Array<!proto.ding4.Photo>} value
 * @return {!proto.ding4.Product} returns this
*/
proto.ding4.Product.prototype.setPhotoxList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.ding4.Photo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ding4.Photo}
 */
proto.ding4.Product.prototype.addPhotox = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.ding4.Photo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.clearPhotoxList = function() {
  return this.setPhotoxList([]);
};


/**
 * optional ProductLink link = 15;
 * @return {?proto.ding4.ProductLink}
 */
proto.ding4.Product.prototype.getLink = function() {
  return /** @type{?proto.ding4.ProductLink} */ (
    jspb.Message.getWrapperField(this, proto.ding4.ProductLink, 15));
};


/**
 * @param {?proto.ding4.ProductLink|undefined} value
 * @return {!proto.ding4.Product} returns this
*/
proto.ding4.Product.prototype.setLink = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.clearLink = function() {
  return this.setLink(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.Product.prototype.hasLink = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * map<string, int32> labelx = 16;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.ding4.Product.prototype.getLabelxMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 16, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.clearLabelxMap = function() {
  this.getLabelxMap().clear();
  return this;};


/**
 * optional string operator = 17;
 * @return {string}
 */
proto.ding4.Product.prototype.getOperator = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.setOperator = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional google.protobuf.Timestamp create_at = 18;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.ding4.Product.prototype.getCreateAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 18));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.ding4.Product} returns this
*/
proto.ding4.Product.prototype.setCreateAt = function(value) {
  return jspb.Message.setWrapperField(this, 18, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.clearCreateAt = function() {
  return this.setCreateAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.Product.prototype.hasCreateAt = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional google.protobuf.Timestamp update_at = 19;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.ding4.Product.prototype.getUpdateAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 19));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.ding4.Product} returns this
*/
proto.ding4.Product.prototype.setUpdateAt = function(value) {
  return jspb.Message.setWrapperField(this, 19, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.clearUpdateAt = function() {
  return this.setUpdateAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.Product.prototype.hasUpdateAt = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * repeated string cols = 20;
 * @return {!Array<string>}
 */
proto.ding4.Product.prototype.getColsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 20));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.setColsList = function(value) {
  return jspb.Message.setField(this, 20, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.addCols = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 20, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.clearColsList = function() {
  return this.setColsList([]);
};


/**
 * repeated Condition condition = 21;
 * @return {!Array<!proto.ding4.Condition>}
 */
proto.ding4.Product.prototype.getConditionList = function() {
  return /** @type{!Array<!proto.ding4.Condition>} */ (
    jspb.Message.getRepeatedWrapperField(this, sql_pb.Condition, 21));
};


/**
 * @param {!Array<!proto.ding4.Condition>} value
 * @return {!proto.ding4.Product} returns this
*/
proto.ding4.Product.prototype.setConditionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 21, value);
};


/**
 * @param {!proto.ding4.Condition=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ding4.Condition}
 */
proto.ding4.Product.prototype.addCondition = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 21, opt_value, proto.ding4.Condition, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.clearConditionList = function() {
  return this.setConditionList([]);
};


/**
 * optional google.protobuf.Struct self = 22;
 * @return {?proto.google.protobuf.Struct}
 */
proto.ding4.Product.prototype.getSelf = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 22));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.ding4.Product} returns this
*/
proto.ding4.Product.prototype.setSelf = function(value) {
  return jspb.Message.setWrapperField(this, 22, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.Product} returns this
 */
proto.ding4.Product.prototype.clearSelf = function() {
  return this.setSelf(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.Product.prototype.hasSelf = function() {
  return jspb.Message.getField(this, 22) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ding4.Spec.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ding4.Spec.prototype.toObject = function(opt_includeInstance) {
  return proto.ding4.Spec.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ding4.Spec} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ding4.Spec.toObject = function(includeInstance, msg) {
  var f, obj = {
    sku: jspb.Message.getFieldWithDefault(msg, 1, ""),
    display: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    stock: jspb.Message.getFieldWithDefault(msg, 3, 0),
    sold: jspb.Message.getFieldWithDefault(msg, 4, 0),
    itemxList: jspb.Message.toObjectList(msg.getItemxList(),
    google_protobuf_struct_pb.Value.toObject, includeInstance),
    photo: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ding4.Spec}
 */
proto.ding4.Spec.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ding4.Spec;
  return proto.ding4.Spec.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ding4.Spec} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ding4.Spec}
 */
proto.ding4.Spec.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSku(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDisplay(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStock(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSold(value);
      break;
    case 5:
      var value = new google_protobuf_struct_pb.Value;
      reader.readMessage(value,google_protobuf_struct_pb.Value.deserializeBinaryFromReader);
      msg.addItemx(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhoto(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ding4.Spec.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ding4.Spec.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ding4.Spec} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ding4.Spec.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSku();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDisplay();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getStock();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getSold();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getItemxList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      google_protobuf_struct_pb.Value.serializeBinaryToWriter
    );
  }
  f = message.getPhoto();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string sku = 1;
 * @return {string}
 */
proto.ding4.Spec.prototype.getSku = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Spec} returns this
 */
proto.ding4.Spec.prototype.setSku = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool display = 2;
 * @return {boolean}
 */
proto.ding4.Spec.prototype.getDisplay = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ding4.Spec} returns this
 */
proto.ding4.Spec.prototype.setDisplay = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional int32 stock = 3;
 * @return {number}
 */
proto.ding4.Spec.prototype.getStock = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.ding4.Spec} returns this
 */
proto.ding4.Spec.prototype.setStock = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 sold = 4;
 * @return {number}
 */
proto.ding4.Spec.prototype.getSold = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.ding4.Spec} returns this
 */
proto.ding4.Spec.prototype.setSold = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * repeated google.protobuf.Value itemx = 5;
 * @return {!Array<!proto.google.protobuf.Value>}
 */
proto.ding4.Spec.prototype.getItemxList = function() {
  return /** @type{!Array<!proto.google.protobuf.Value>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_protobuf_struct_pb.Value, 5));
};


/**
 * @param {!Array<!proto.google.protobuf.Value>} value
 * @return {!proto.ding4.Spec} returns this
*/
proto.ding4.Spec.prototype.setItemxList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.google.protobuf.Value=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.Value}
 */
proto.ding4.Spec.prototype.addItemx = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.google.protobuf.Value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ding4.Spec} returns this
 */
proto.ding4.Spec.prototype.clearItemxList = function() {
  return this.setItemxList([]);
};


/**
 * optional string photo = 6;
 * @return {string}
 */
proto.ding4.Spec.prototype.getPhoto = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Spec} returns this
 */
proto.ding4.Spec.prototype.setPhoto = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ding4.Photo.prototype.toObject = function(opt_includeInstance) {
  return proto.ding4.Photo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ding4.Photo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ding4.Photo.toObject = function(includeInstance, msg) {
  var f, obj = {
    h: jspb.Message.getFieldWithDefault(msg, 1, ""),
    p: jspb.Message.getFieldWithDefault(msg, 2, ""),
    n: jspb.Message.getFieldWithDefault(msg, 3, ""),
    e: jspb.Message.getFieldWithDefault(msg, 4, ""),
    i: jspb.Message.getFieldWithDefault(msg, 5, 0),
    sku: jspb.Message.getFieldWithDefault(msg, 6, ""),
    source: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ding4.Photo}
 */
proto.ding4.Photo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ding4.Photo;
  return proto.ding4.Photo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ding4.Photo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ding4.Photo}
 */
proto.ding4.Photo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setH(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setP(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setN(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setE(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setI(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setSku(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setSource(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ding4.Photo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ding4.Photo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ding4.Photo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ding4.Photo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getH();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getP();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getN();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getE();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getI();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getSku();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getSource();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string h = 1;
 * @return {string}
 */
proto.ding4.Photo.prototype.getH = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Photo} returns this
 */
proto.ding4.Photo.prototype.setH = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string p = 2;
 * @return {string}
 */
proto.ding4.Photo.prototype.getP = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Photo} returns this
 */
proto.ding4.Photo.prototype.setP = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string n = 3;
 * @return {string}
 */
proto.ding4.Photo.prototype.getN = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Photo} returns this
 */
proto.ding4.Photo.prototype.setN = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string e = 4;
 * @return {string}
 */
proto.ding4.Photo.prototype.getE = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Photo} returns this
 */
proto.ding4.Photo.prototype.setE = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 i = 5;
 * @return {number}
 */
proto.ding4.Photo.prototype.getI = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.ding4.Photo} returns this
 */
proto.ding4.Photo.prototype.setI = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string sku = 6;
 * @return {string}
 */
proto.ding4.Photo.prototype.getSku = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Photo} returns this
 */
proto.ding4.Photo.prototype.setSku = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string source = 7;
 * @return {string}
 */
proto.ding4.Photo.prototype.getSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Photo} returns this
 */
proto.ding4.Photo.prototype.setSource = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ding4.ProductLink.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ding4.ProductLink.prototype.toObject = function(opt_includeInstance) {
  return proto.ding4.ProductLink.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ding4.ProductLink} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ding4.ProductLink.toObject = function(includeInstance, msg) {
  var f, obj = {
    productId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    classId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    isDisplay: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    url: jspb.Message.getFieldWithDefault(msg, 4, ""),
    freightAdd: jspb.Message.getFieldWithDefault(msg, 5, 0),
    seo: (f = msg.getSeo()) && seo_pb.SEO.toObject(includeInstance, f),
    blockList: jspb.Message.toObjectList(msg.getBlockList(),
    seo_pb.Block.toObject, includeInstance),
    self: (f = msg.getSelf()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ding4.ProductLink}
 */
proto.ding4.ProductLink.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ding4.ProductLink;
  return proto.ding4.ProductLink.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ding4.ProductLink} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ding4.ProductLink}
 */
proto.ding4.ProductLink.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setClassId(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsDisplay(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFreightAdd(value);
      break;
    case 6:
      var value = new seo_pb.SEO;
      reader.readMessage(value,seo_pb.SEO.deserializeBinaryFromReader);
      msg.setSeo(value);
      break;
    case 7:
      var value = new seo_pb.Block;
      reader.readMessage(value,seo_pb.Block.deserializeBinaryFromReader);
      msg.addBlock(value);
      break;
    case 8:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setSelf(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ding4.ProductLink.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ding4.ProductLink.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ding4.ProductLink} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ding4.ProductLink.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProductId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getClassId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getIsDisplay();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getFreightAdd();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getSeo();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      seo_pb.SEO.serializeBinaryToWriter
    );
  }
  f = message.getBlockList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      seo_pb.Block.serializeBinaryToWriter
    );
  }
  f = message.getSelf();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
};


/**
 * optional string product_id = 1;
 * @return {string}
 */
proto.ding4.ProductLink.prototype.getProductId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.ProductLink} returns this
 */
proto.ding4.ProductLink.prototype.setProductId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string class_id = 2;
 * @return {string}
 */
proto.ding4.ProductLink.prototype.getClassId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.ProductLink} returns this
 */
proto.ding4.ProductLink.prototype.setClassId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool is_display = 3;
 * @return {boolean}
 */
proto.ding4.ProductLink.prototype.getIsDisplay = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ding4.ProductLink} returns this
 */
proto.ding4.ProductLink.prototype.setIsDisplay = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional string url = 4;
 * @return {string}
 */
proto.ding4.ProductLink.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.ProductLink} returns this
 */
proto.ding4.ProductLink.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 freight_add = 5;
 * @return {number}
 */
proto.ding4.ProductLink.prototype.getFreightAdd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.ding4.ProductLink} returns this
 */
proto.ding4.ProductLink.prototype.setFreightAdd = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional SEO seo = 6;
 * @return {?proto.ding4.SEO}
 */
proto.ding4.ProductLink.prototype.getSeo = function() {
  return /** @type{?proto.ding4.SEO} */ (
    jspb.Message.getWrapperField(this, seo_pb.SEO, 6));
};


/**
 * @param {?proto.ding4.SEO|undefined} value
 * @return {!proto.ding4.ProductLink} returns this
*/
proto.ding4.ProductLink.prototype.setSeo = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.ProductLink} returns this
 */
proto.ding4.ProductLink.prototype.clearSeo = function() {
  return this.setSeo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.ProductLink.prototype.hasSeo = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated Block block = 7;
 * @return {!Array<!proto.ding4.Block>}
 */
proto.ding4.ProductLink.prototype.getBlockList = function() {
  return /** @type{!Array<!proto.ding4.Block>} */ (
    jspb.Message.getRepeatedWrapperField(this, seo_pb.Block, 7));
};


/**
 * @param {!Array<!proto.ding4.Block>} value
 * @return {!proto.ding4.ProductLink} returns this
*/
proto.ding4.ProductLink.prototype.setBlockList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.ding4.Block=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ding4.Block}
 */
proto.ding4.ProductLink.prototype.addBlock = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.ding4.Block, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ding4.ProductLink} returns this
 */
proto.ding4.ProductLink.prototype.clearBlockList = function() {
  return this.setBlockList([]);
};


/**
 * optional google.protobuf.Struct self = 8;
 * @return {?proto.google.protobuf.Struct}
 */
proto.ding4.ProductLink.prototype.getSelf = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 8));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.ding4.ProductLink} returns this
*/
proto.ding4.ProductLink.prototype.setSelf = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.ProductLink} returns this
 */
proto.ding4.ProductLink.prototype.clearSelf = function() {
  return this.setSelf(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.ProductLink.prototype.hasSelf = function() {
  return jspb.Message.getField(this, 8) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ding4.ProductSpec.repeatedFields_ = [13,14];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ding4.ProductSpec.prototype.toObject = function(opt_includeInstance) {
  return proto.ding4.ProductSpec.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ding4.ProductSpec} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ding4.ProductSpec.toObject = function(includeInstance, msg) {
  var f, obj = {
    productSpecId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    productId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    status: jspb.Message.getFieldWithDefault(msg, 3, 0),
    spec1: (f = msg.getSpec1()) && google_protobuf_struct_pb.Value.toObject(includeInstance, f),
    spec2: (f = msg.getSpec2()) && google_protobuf_struct_pb.Value.toObject(includeInstance, f),
    spec3: (f = msg.getSpec3()) && google_protobuf_struct_pb.Value.toObject(includeInstance, f),
    sku: jspb.Message.getFieldWithDefault(msg, 7, ""),
    photo: jspb.Message.getFieldWithDefault(msg, 8, ""),
    image: (f = msg.getImage()) && image_pb.Image.toObject(includeInstance, f),
    operator: jspb.Message.getFieldWithDefault(msg, 10, ""),
    createAt: (f = msg.getCreateAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updateAt: (f = msg.getUpdateAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    colsList: (f = jspb.Message.getRepeatedField(msg, 13)) == null ? undefined : f,
    conditionList: jspb.Message.toObjectList(msg.getConditionList(),
    sql_pb.Condition.toObject, includeInstance),
    self: (f = msg.getSelf()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ding4.ProductSpec}
 */
proto.ding4.ProductSpec.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ding4.ProductSpec;
  return proto.ding4.ProductSpec.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ding4.ProductSpec} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ding4.ProductSpec}
 */
proto.ding4.ProductSpec.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductSpecId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStatus(value);
      break;
    case 4:
      var value = new google_protobuf_struct_pb.Value;
      reader.readMessage(value,google_protobuf_struct_pb.Value.deserializeBinaryFromReader);
      msg.setSpec1(value);
      break;
    case 5:
      var value = new google_protobuf_struct_pb.Value;
      reader.readMessage(value,google_protobuf_struct_pb.Value.deserializeBinaryFromReader);
      msg.setSpec2(value);
      break;
    case 6:
      var value = new google_protobuf_struct_pb.Value;
      reader.readMessage(value,google_protobuf_struct_pb.Value.deserializeBinaryFromReader);
      msg.setSpec3(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setSku(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhoto(value);
      break;
    case 9:
      var value = new image_pb.Image;
      reader.readMessage(value,image_pb.Image.deserializeBinaryFromReader);
      msg.setImage(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setOperator(value);
      break;
    case 11:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreateAt(value);
      break;
    case 12:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdateAt(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.addCols(value);
      break;
    case 14:
      var value = new sql_pb.Condition;
      reader.readMessage(value,sql_pb.Condition.deserializeBinaryFromReader);
      msg.addCondition(value);
      break;
    case 15:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setSelf(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ding4.ProductSpec.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ding4.ProductSpec.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ding4.ProductSpec} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ding4.ProductSpec.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProductSpecId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProductId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getSpec1();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_struct_pb.Value.serializeBinaryToWriter
    );
  }
  f = message.getSpec2();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_struct_pb.Value.serializeBinaryToWriter
    );
  }
  f = message.getSpec3();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_struct_pb.Value.serializeBinaryToWriter
    );
  }
  f = message.getSku();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getPhoto();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getImage();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      image_pb.Image.serializeBinaryToWriter
    );
  }
  f = message.getOperator();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getCreateAt();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdateAt();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getColsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      13,
      f
    );
  }
  f = message.getConditionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      14,
      f,
      sql_pb.Condition.serializeBinaryToWriter
    );
  }
  f = message.getSelf();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
};


/**
 * optional string product_spec_id = 1;
 * @return {string}
 */
proto.ding4.ProductSpec.prototype.getProductSpecId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.setProductSpecId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string product_id = 2;
 * @return {string}
 */
proto.ding4.ProductSpec.prototype.getProductId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.setProductId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 status = 3;
 * @return {number}
 */
proto.ding4.ProductSpec.prototype.getStatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.setStatus = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional google.protobuf.Value spec1 = 4;
 * @return {?proto.google.protobuf.Value}
 */
proto.ding4.ProductSpec.prototype.getSpec1 = function() {
  return /** @type{?proto.google.protobuf.Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Value, 4));
};


/**
 * @param {?proto.google.protobuf.Value|undefined} value
 * @return {!proto.ding4.ProductSpec} returns this
*/
proto.ding4.ProductSpec.prototype.setSpec1 = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.clearSpec1 = function() {
  return this.setSpec1(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.ProductSpec.prototype.hasSpec1 = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Value spec2 = 5;
 * @return {?proto.google.protobuf.Value}
 */
proto.ding4.ProductSpec.prototype.getSpec2 = function() {
  return /** @type{?proto.google.protobuf.Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Value, 5));
};


/**
 * @param {?proto.google.protobuf.Value|undefined} value
 * @return {!proto.ding4.ProductSpec} returns this
*/
proto.ding4.ProductSpec.prototype.setSpec2 = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.clearSpec2 = function() {
  return this.setSpec2(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.ProductSpec.prototype.hasSpec2 = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Value spec3 = 6;
 * @return {?proto.google.protobuf.Value}
 */
proto.ding4.ProductSpec.prototype.getSpec3 = function() {
  return /** @type{?proto.google.protobuf.Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Value, 6));
};


/**
 * @param {?proto.google.protobuf.Value|undefined} value
 * @return {!proto.ding4.ProductSpec} returns this
*/
proto.ding4.ProductSpec.prototype.setSpec3 = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.clearSpec3 = function() {
  return this.setSpec3(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.ProductSpec.prototype.hasSpec3 = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string sku = 7;
 * @return {string}
 */
proto.ding4.ProductSpec.prototype.getSku = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.setSku = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string photo = 8;
 * @return {string}
 */
proto.ding4.ProductSpec.prototype.getPhoto = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.setPhoto = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional Image image = 9;
 * @return {?proto.ding4.Image}
 */
proto.ding4.ProductSpec.prototype.getImage = function() {
  return /** @type{?proto.ding4.Image} */ (
    jspb.Message.getWrapperField(this, image_pb.Image, 9));
};


/**
 * @param {?proto.ding4.Image|undefined} value
 * @return {!proto.ding4.ProductSpec} returns this
*/
proto.ding4.ProductSpec.prototype.setImage = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.clearImage = function() {
  return this.setImage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.ProductSpec.prototype.hasImage = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional string operator = 10;
 * @return {string}
 */
proto.ding4.ProductSpec.prototype.getOperator = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.setOperator = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional google.protobuf.Timestamp create_at = 11;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.ding4.ProductSpec.prototype.getCreateAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 11));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.ding4.ProductSpec} returns this
*/
proto.ding4.ProductSpec.prototype.setCreateAt = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.clearCreateAt = function() {
  return this.setCreateAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.ProductSpec.prototype.hasCreateAt = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional google.protobuf.Timestamp update_at = 12;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.ding4.ProductSpec.prototype.getUpdateAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 12));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.ding4.ProductSpec} returns this
*/
proto.ding4.ProductSpec.prototype.setUpdateAt = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.clearUpdateAt = function() {
  return this.setUpdateAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.ProductSpec.prototype.hasUpdateAt = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * repeated string cols = 13;
 * @return {!Array<string>}
 */
proto.ding4.ProductSpec.prototype.getColsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 13));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.setColsList = function(value) {
  return jspb.Message.setField(this, 13, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.addCols = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 13, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.clearColsList = function() {
  return this.setColsList([]);
};


/**
 * repeated Condition condition = 14;
 * @return {!Array<!proto.ding4.Condition>}
 */
proto.ding4.ProductSpec.prototype.getConditionList = function() {
  return /** @type{!Array<!proto.ding4.Condition>} */ (
    jspb.Message.getRepeatedWrapperField(this, sql_pb.Condition, 14));
};


/**
 * @param {!Array<!proto.ding4.Condition>} value
 * @return {!proto.ding4.ProductSpec} returns this
*/
proto.ding4.ProductSpec.prototype.setConditionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 14, value);
};


/**
 * @param {!proto.ding4.Condition=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ding4.Condition}
 */
proto.ding4.ProductSpec.prototype.addCondition = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 14, opt_value, proto.ding4.Condition, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.clearConditionList = function() {
  return this.setConditionList([]);
};


/**
 * optional google.protobuf.Struct self = 15;
 * @return {?proto.google.protobuf.Struct}
 */
proto.ding4.ProductSpec.prototype.getSelf = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 15));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.ding4.ProductSpec} returns this
*/
proto.ding4.ProductSpec.prototype.setSelf = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.ProductSpec} returns this
 */
proto.ding4.ProductSpec.prototype.clearSelf = function() {
  return this.setSelf(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.ProductSpec.prototype.hasSelf = function() {
  return jspb.Message.getField(this, 15) != null;
};


goog.object.extend(exports, proto.ding4);
