// source: message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
goog.exportSymbol('proto.ding4.Message', null, global);
goog.exportSymbol('proto.ding4.Message.User', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ding4.Message = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ding4.Message.repeatedFields_, null);
};
goog.inherits(proto.ding4.Message, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ding4.Message.displayName = 'proto.ding4.Message';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ding4.Message.User = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ding4.Message.User, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ding4.Message.User.displayName = 'proto.ding4.Message.User';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ding4.Message.repeatedFields_ = [15,21];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ding4.Message.prototype.toObject = function(opt_includeInstance) {
  return proto.ding4.Message.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ding4.Message} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ding4.Message.toObject = function(includeInstance, msg) {
  var f, obj = {
    messageId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    businessId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    storeId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    state: jspb.Message.getFieldWithDefault(msg, 4, 0),
    category: jspb.Message.getFieldWithDefault(msg, 5, 0),
    service: jspb.Message.getFieldWithDefault(msg, 6, ""),
    remindEvent: jspb.Message.getFieldWithDefault(msg, 7, ""),
    total: jspb.Message.getFieldWithDefault(msg, 8, 0),
    success: jspb.Message.getFieldWithDefault(msg, 9, 0),
    charge: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0),
    response: (f = msg.getResponse()) && google_protobuf_struct_pb.Value.toObject(includeInstance, f),
    subject: jspb.Message.getFieldWithDefault(msg, 12, ""),
    content: jspb.Message.getFieldWithDefault(msg, 13, ""),
    fromUser: (f = msg.getFromUser()) && proto.ding4.Message.User.toObject(includeInstance, f),
    toUserList: jspb.Message.toObjectList(msg.getToUserList(),
    proto.ding4.Message.User.toObject, includeInstance),
    scheduledTime: (f = msg.getScheduledTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    openedMap: (f = msg.getOpenedMap()) ? f.toObject(includeInstance, undefined) : [],
    operator: jspb.Message.getFieldWithDefault(msg, 18, ""),
    createAt: (f = msg.getCreateAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updateAt: (f = msg.getUpdateAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    colsList: (f = jspb.Message.getRepeatedField(msg, 21)) == null ? undefined : f,
    self: (f = msg.getSelf()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ding4.Message}
 */
proto.ding4.Message.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ding4.Message;
  return proto.ding4.Message.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ding4.Message} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ding4.Message}
 */
proto.ding4.Message.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessageId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBusinessId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStoreId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setState(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCategory(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setService(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setRemindEvent(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotal(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSuccess(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCharge(value);
      break;
    case 11:
      var value = new google_protobuf_struct_pb.Value;
      reader.readMessage(value,google_protobuf_struct_pb.Value.deserializeBinaryFromReader);
      msg.setResponse(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubject(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 14:
      var value = new proto.ding4.Message.User;
      reader.readMessage(value,proto.ding4.Message.User.deserializeBinaryFromReader);
      msg.setFromUser(value);
      break;
    case 15:
      var value = new proto.ding4.Message.User;
      reader.readMessage(value,proto.ding4.Message.User.deserializeBinaryFromReader);
      msg.addToUser(value);
      break;
    case 16:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setScheduledTime(value);
      break;
    case 17:
      var value = msg.getOpenedMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readInt32, null, "", 0);
         });
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setOperator(value);
      break;
    case 19:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreateAt(value);
      break;
    case 20:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdateAt(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.addCols(value);
      break;
    case 22:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setSelf(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ding4.Message.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ding4.Message.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ding4.Message} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ding4.Message.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessageId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBusinessId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStoreId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getState();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getCategory();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getService();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getRemindEvent();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getTotal();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getSuccess();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getCharge();
  if (f !== 0.0) {
    writer.writeDouble(
      10,
      f
    );
  }
  f = message.getResponse();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_struct_pb.Value.serializeBinaryToWriter
    );
  }
  f = message.getSubject();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getFromUser();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      proto.ding4.Message.User.serializeBinaryToWriter
    );
  }
  f = message.getToUserList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      15,
      f,
      proto.ding4.Message.User.serializeBinaryToWriter
    );
  }
  f = message.getScheduledTime();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getOpenedMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(17, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeInt32);
  }
  f = message.getOperator();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getCreateAt();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdateAt();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getColsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      21,
      f
    );
  }
  f = message.getSelf();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ding4.Message.User.prototype.toObject = function(opt_includeInstance) {
  return proto.ding4.Message.User.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ding4.Message.User} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ding4.Message.User.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    sex: jspb.Message.getFieldWithDefault(msg, 2, ""),
    email: jspb.Message.getFieldWithDefault(msg, 3, ""),
    phone: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ding4.Message.User}
 */
proto.ding4.Message.User.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ding4.Message.User;
  return proto.ding4.Message.User.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ding4.Message.User} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ding4.Message.User}
 */
proto.ding4.Message.User.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSex(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhone(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ding4.Message.User.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ding4.Message.User.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ding4.Message.User} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ding4.Message.User.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSex();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPhone();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.ding4.Message.User.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Message.User} returns this
 */
proto.ding4.Message.User.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string sex = 2;
 * @return {string}
 */
proto.ding4.Message.User.prototype.getSex = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Message.User} returns this
 */
proto.ding4.Message.User.prototype.setSex = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string email = 3;
 * @return {string}
 */
proto.ding4.Message.User.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Message.User} returns this
 */
proto.ding4.Message.User.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string phone = 4;
 * @return {string}
 */
proto.ding4.Message.User.prototype.getPhone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Message.User} returns this
 */
proto.ding4.Message.User.prototype.setPhone = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string message_id = 1;
 * @return {string}
 */
proto.ding4.Message.prototype.getMessageId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.setMessageId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string business_id = 2;
 * @return {string}
 */
proto.ding4.Message.prototype.getBusinessId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.setBusinessId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string store_id = 3;
 * @return {string}
 */
proto.ding4.Message.prototype.getStoreId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.setStoreId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 state = 4;
 * @return {number}
 */
proto.ding4.Message.prototype.getState = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.setState = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 category = 5;
 * @return {number}
 */
proto.ding4.Message.prototype.getCategory = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.setCategory = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string service = 6;
 * @return {string}
 */
proto.ding4.Message.prototype.getService = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.setService = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string remind_event = 7;
 * @return {string}
 */
proto.ding4.Message.prototype.getRemindEvent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.setRemindEvent = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional int32 total = 8;
 * @return {number}
 */
proto.ding4.Message.prototype.getTotal = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.setTotal = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int32 success = 9;
 * @return {number}
 */
proto.ding4.Message.prototype.getSuccess = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional double charge = 10;
 * @return {number}
 */
proto.ding4.Message.prototype.getCharge = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.setCharge = function(value) {
  return jspb.Message.setProto3FloatField(this, 10, value);
};


/**
 * optional google.protobuf.Value response = 11;
 * @return {?proto.google.protobuf.Value}
 */
proto.ding4.Message.prototype.getResponse = function() {
  return /** @type{?proto.google.protobuf.Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Value, 11));
};


/**
 * @param {?proto.google.protobuf.Value|undefined} value
 * @return {!proto.ding4.Message} returns this
*/
proto.ding4.Message.prototype.setResponse = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.clearResponse = function() {
  return this.setResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.Message.prototype.hasResponse = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional string subject = 12;
 * @return {string}
 */
proto.ding4.Message.prototype.getSubject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.setSubject = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string content = 13;
 * @return {string}
 */
proto.ding4.Message.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.setContent = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional User from_user = 14;
 * @return {?proto.ding4.Message.User}
 */
proto.ding4.Message.prototype.getFromUser = function() {
  return /** @type{?proto.ding4.Message.User} */ (
    jspb.Message.getWrapperField(this, proto.ding4.Message.User, 14));
};


/**
 * @param {?proto.ding4.Message.User|undefined} value
 * @return {!proto.ding4.Message} returns this
*/
proto.ding4.Message.prototype.setFromUser = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.clearFromUser = function() {
  return this.setFromUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.Message.prototype.hasFromUser = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * repeated User to_user = 15;
 * @return {!Array<!proto.ding4.Message.User>}
 */
proto.ding4.Message.prototype.getToUserList = function() {
  return /** @type{!Array<!proto.ding4.Message.User>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ding4.Message.User, 15));
};


/**
 * @param {!Array<!proto.ding4.Message.User>} value
 * @return {!proto.ding4.Message} returns this
*/
proto.ding4.Message.prototype.setToUserList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 15, value);
};


/**
 * @param {!proto.ding4.Message.User=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ding4.Message.User}
 */
proto.ding4.Message.prototype.addToUser = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 15, opt_value, proto.ding4.Message.User, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.clearToUserList = function() {
  return this.setToUserList([]);
};


/**
 * optional google.protobuf.Timestamp scheduled_time = 16;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.ding4.Message.prototype.getScheduledTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 16));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.ding4.Message} returns this
*/
proto.ding4.Message.prototype.setScheduledTime = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.clearScheduledTime = function() {
  return this.setScheduledTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.Message.prototype.hasScheduledTime = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * map<string, int32> opened = 17;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.ding4.Message.prototype.getOpenedMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 17, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.clearOpenedMap = function() {
  this.getOpenedMap().clear();
  return this;};


/**
 * optional string operator = 18;
 * @return {string}
 */
proto.ding4.Message.prototype.getOperator = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.setOperator = function(value) {
  return jspb.Message.setProto3StringField(this, 18, value);
};


/**
 * optional google.protobuf.Timestamp create_at = 19;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.ding4.Message.prototype.getCreateAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 19));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.ding4.Message} returns this
*/
proto.ding4.Message.prototype.setCreateAt = function(value) {
  return jspb.Message.setWrapperField(this, 19, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.clearCreateAt = function() {
  return this.setCreateAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.Message.prototype.hasCreateAt = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional google.protobuf.Timestamp update_at = 20;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.ding4.Message.prototype.getUpdateAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 20));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.ding4.Message} returns this
*/
proto.ding4.Message.prototype.setUpdateAt = function(value) {
  return jspb.Message.setWrapperField(this, 20, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.clearUpdateAt = function() {
  return this.setUpdateAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.Message.prototype.hasUpdateAt = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * repeated string cols = 21;
 * @return {!Array<string>}
 */
proto.ding4.Message.prototype.getColsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 21));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.setColsList = function(value) {
  return jspb.Message.setField(this, 21, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.addCols = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 21, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.clearColsList = function() {
  return this.setColsList([]);
};


/**
 * optional google.protobuf.Struct self = 22;
 * @return {?proto.google.protobuf.Struct}
 */
proto.ding4.Message.prototype.getSelf = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 22));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.ding4.Message} returns this
*/
proto.ding4.Message.prototype.setSelf = function(value) {
  return jspb.Message.setWrapperField(this, 22, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ding4.Message} returns this
 */
proto.ding4.Message.prototype.clearSelf = function() {
  return this.setSelf(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ding4.Message.prototype.hasSelf = function() {
  return jspb.Message.getField(this, 22) != null;
};


goog.object.extend(exports, proto.ding4);
